In [3]:
import pandas as pd

# Load the Excel file into a pandas DataFrame
file_path = r'C:\Users\olich\Downloads\datasets\Print Adex Dump FY 22 & 23.xlsx'  # Update with your file path
df = pd.read_excel(file_path)
df.head()

,PERIOD,MEDIUM,SUPER CATEGORY,ADVERTISER,PRODUCT,PUB NATURE,PUBLICATION,PUB LANGUAGE,STATE,FREQUENCY,VOL_CC,VOL_SQCM,TAM COST,BASE_COST
0,Apr 2021 - Jun 2021,PRINT,Agriculture,Aastha Organics,Aastha Organics,Newspaper,Dainik Jagran-jammu,Hindi,Jammu & Kashmir,1,7,28,14,14
1,Apr 2021 - Jun 2021,PRINT,Agriculture,Abhimanyu Seeds Pvt Ltd,Abhimanyu Abhi-09,Newspaper,Dainik Jagran-jhn,Hindi,Uttar Pradesh,2,40,200,136,109
2,Apr 2021 - Jun 2021,PRINT,Agriculture,Abhimanyu Seeds Pvt Ltd,Abhimanyu Kanhaiya,Newspaper,Dainik Jagran-jhn,Hindi,Uttar Pradesh,1,20,100,70,56
3,Apr 2021 - Jun 2021,PRINT,Agriculture,Abhimanyu Seeds Pvt Ltd,Abhimanyu Magic Gold,Newspaper,Dainik Jagran-jhn,Hindi,Uttar Pradesh,2,40,200,141,113
4,Apr 2021 - Jun 2021,PRINT,Agriculture,Abhimanyu Seeds Pvt Ltd,Abhimanyu Sampanna,Newspaper,Dainik Jagran-jhn,Hindi,Uttar Pradesh,3,60,300,201,161